language: python
python:
  - "2.7"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install pytest"
# command to run tests, e.g. python setup.py test
script: py.test applications/paideia/tests/modules/test_paideia.py 
